### ISSUE TITLE
Keep the plane moving

### ISSUE THREAD

**Issue by fdciabdul** [Glowstick0017/Little-Plane-Project#35]
**Is your feature request related to a problem? Please describe.** 
There seems to be a problem where the plane doesn't continue moving when controls are clicked, or possibly waits for another control input before proceeding.

**Describe the solution you'd like** 
To improve the user experience, the plane should behave similar to the mechanics observed in IO games. Specifically, after an initial control is clicked or given, the plane should keep moving forward, regardless of whether any additional controls are provided. It should not freeze or wait for another control to be clicked.

**Describe alternatives you've considered** 

**Additional context**
 By implementing this feature, we can enhance the game flow and user experience. Continuous movement, similar to the mechanics in IO games, is essential for making the gameplay feel more fluid and intuitive.

**Comment by Glowstick0017** [comment]
I like the idea, right now the plane only moves as the user inputs because originally the plane didn’t exist and it was just moving the screen to see the map of generation. I thought about adding a key that when pressed will keep the plane moving, but maybe it would be better the other way around, the plane would be constantly moving and a user can stop the planes movement to move more precisely kind of like a creative mode.

**Comment by Glowstick0017** [comment]
added 'e' key as toggle for constant flight in https://github.com/Glowstick0017/Little-Plane-Project/commit/3acc86fbb5acba561c12a82fa2f0d80d5fcb45c9
